# route description

from = Sofia
# to = Varna # my favourite city! # edited at Thu Apr 16 21:48:24 EEST 2026 by s0600470
to = Plovdiv # added at Thu Apr 16 21:48:24 EEST 2026 by s0600470
type = t2_1
